spring:
  application:
    name: ZapolyarnyNewsBot
  datasource:
    url: jdbc:postgresql://localhost:5432/news-bot-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  messages:
    encoding: UTF-8
    basename: i18n/messages
    fallback-to-system-locale: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

telegram:
  bot:
    username: ZapolyarnyNewsBot
    token: 8125380161:AAHaeYMPKMFp_8-yI1o3P6Fyv7dL4DWgcrc