spring:
  application:
    name: ZapolyarnyNewsBot
  messages:
    encoding: UTF-8
    basename: i18n/messages
    fallback-to-system-locale: false

server:
  port: 8081

telegram:
  bot:
    username: ZapolyarnyNewsBot
    token: 8125380161:AAHaeYMPKMFp_8-yI1o3P6Fyv7dL4DWgcrc